//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondSword.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiamondSword.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Textures....
        /// </summary>
        public static string Button_ImportTextures {
            get {
                return ResourceManager.GetString("Button_ImportTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder containing block textures (PNG).
        /// </summary>
        public static string Dialog_SelectFolder {
            get {
                return ResourceManager.GetString("Dialog_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click an item to copy Minecraft /give command to clipboard..
        /// </summary>
        public static string Instruction_ClickItem {
            get {
                return ResourceManager.GetString("Instruction_ClickItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Filter .
        /// </summary>
        public static string Label_AlphaFilter {
            get {
                return ResourceManager.GetString("Label_AlphaFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string Label_B {
            get {
                return ResourceManager.GetString("Label_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks to show.
        /// </summary>
        public static string Label_BlocksToShow {
            get {
                return ResourceManager.GetString("Label_BlocksToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color (RGB).
        /// </summary>
        public static string Label_ColorRGB {
            get {
                return ResourceManager.GetString("Label_ColorRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        public static string Label_G {
            get {
                return ResourceManager.GetString("Label_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string Label_R {
            get {
                return ResourceManager.GetString("Label_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied: /give @p {0} 10.
        /// </summary>
        public static string Message_Copied {
            get {
                return ResourceManager.GetString("Message_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        public static string Message_Copied_Title {
            get {
                return ResourceManager.GetString("Message_Copied_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Message_Error_Title {
            get {
                return ResourceManager.GetString("Message_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid positive integer for amount..
        /// </summary>
        public static string Message_InvalidAmount {
            get {
                return ResourceManager.GetString("Message_InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No blocks.cfg found. Please import textures (the folder containing block PNGs)..
        /// </summary>
        public static string Message_NoBlocksCfg {
            get {
                return ResourceManager.GetString("Message_NoBlocksCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No PNG files found in folder..
        /// </summary>
        public static string Message_NoPngFound {
            get {
                return ResourceManager.GetString("Message_NoPngFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string Message_Notice_Title {
            get {
                return ResourceManager.GetString("Message_Notice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchblox.
        /// </summary>
        public static string Window_Title_BlockMatcher {
            get {
                return ResourceManager.GetString("Window_Title_BlockMatcher", resourceCulture);
            }
        }
    }
}
